-- BASE DE DATOS PARA EL SISTEMA DE GESTIÓN DE CASOS JURÍDICOS DE LEGALPRO

-- TABLA PARA ALMACENAR ENTIDADES (CLIENTES Y EMPLEADOS)
CREATE TABLE ENTIDAD (
                         ID SERIAL PRIMARY KEY,
                         NOMBRECOMPLETO VARCHAR(255) NOT NULL,
                         EMAIL VARCHAR(255) NOT NULL UNIQUE,
                         TELEFONO VARCHAR(20),
                         DIRECCION TEXT,
                         FECHAREGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- TABLA PARA LOS ROLES DE LAS ENTIDADES
CREATE TABLE ROL (
                       ID SERIAL PRIMARY KEY,
                       NOMBREROL VARCHAR(50) NOT NULL UNIQUE -- EJEMPLO: 'EMPLEADO', 'CLIENTE'
);

-- TABLA INTERMEDIA PARA LA RELACIÓN MUCHOS A MUCHOS ENTRE ENTIDAD Y ROLES
CREATE TABLE ENTIDADROL (
                               ID SERIAL PRIMARY KEY,
                               ENTIDADID INT NOT NULL REFERENCES ENTIDAD(ID) ON DELETE CASCADE,
                               ROLID INT NOT NULL REFERENCES ROL(ID) ON DELETE CASCADE
);

-- TABLA PARA ALMACENAR LOS CASOS LEGALES
CREATE TABLE CASO (
                       ID SERIAL PRIMARY KEY,
                       CODIGOREFERENCIA VARCHAR(50) NOT NULL UNIQUE,
                       CLIENTEID INT NOT NULL REFERENCES ENTIDAD(ID) ON DELETE CASCADE,
                       EMPLEADOID INT NOT NULL REFERENCES ENTIDAD(ID) ON DELETE CASCADE,
                       TIPOCASO VARCHAR(100) NOT NULL,
                       FECHAINICIO DATE NOT NULL,
                       DETALLES TEXT,
                       ESTADO VARCHAR(50) DEFAULT 'EN PROGRESO',
                       FECHACREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- TABLA PARA GESTIONAR PLAZOS Y EVENTOS DEL CALENDARIO
CREATE TABLE PLAZO (
                        ID SERIAL PRIMARY KEY,
                        CASOID INT NOT NULL REFERENCES CASO(ID) ON DELETE CASCADE,
                        TITULO VARCHAR(255) NOT NULL,
                        DESCRIPCION TEXT,
                        FECHAEVENTO DATE NOT NULL,
                        RECORDATORIO BOOLEAN DEFAULT TRUE,
                        NOTIFICADO BOOLEAN DEFAULT FALSE,
                        FECHACREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- TABLA PARA GESTIONAR TAREAS ASIGNADAS
CREATE TABLE TAREA (
                        ID SERIAL PRIMARY KEY,
                        CASOID INT NOT NULL REFERENCES CASO(ID) ON DELETE CASCADE,
                        TITULO VARCHAR(255) NOT NULL,
                        DESCRIPCION TEXT,
                        RESPONSABLEID INT NOT NULL REFERENCES ENTIDAD(ID),
                        FECHALIMITE DATE NOT NULL,
                        PRIORIDAD VARCHAR(50) DEFAULT 'MEDIA',
                        ESTADO VARCHAR(50) DEFAULT 'PENDIENTE',
                        FECHACREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- TABLA PARA ALMACENAR EL PROGRESO Y EVIDENCIAS DE LAS TAREAS
CREATE TABLE SEGUIMIENTOTAREA (
                                    ID SERIAL PRIMARY KEY,
                                    TAREAID INT NOT NULL REFERENCES TAREA(ID) ON DELETE CASCADE,
                                    COMENTARIO TEXT,
                                    EVIDENCIA BYTEA,
                                    ESTADO VARCHAR(50),
                                    FECHAACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- TABLA PARA ALMACENAR EL ACCESO DE LOS CLIENTES AL PORTAL
CREATE TABLE ACCESOSCLIENTES (
                                  ID SERIAL PRIMARY KEY,
                                  CLIENTEID INT NOT NULL REFERENCES ENTIDAD(ID) ON DELETE CASCADE,
                                  CASOid INT NOT NULL REFERENCES CASO(ID) ON DELETE CASCADE,
                                  FECHAACCESO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
